project_id: 5
api_token_env: CROWDIN_PERSONAL_TOKEN
base_url: https://unraid.api.crowdin.com
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    type: mdx_v2
    # Translation workflow settings
    update_option: update_without_changes
    skip_untranslated_strings: false
    skip_untranslated_files: false
    export_only_approved: false
    # MDX-specific settings to preserve components
    dest: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    translate_attributes: false
    translate_content: true
  # MDX files
  - source: /docs/**/*.mdx
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    type: mdx_v2
    # Translation workflow settings
    update_option: update_without_changes
    skip_untranslated_strings: false
    skip_untranslated_files: false
    export_only_approved: false
    # MDX-specific settings to preserve components
    dest: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    translate_attributes: false
    translate_content: true
  # JSON and other files
  - source: /docs/**/*.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    update_option: update_without_changes
  # Images
  - source: /docs/**/*.png
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    update_option: update_without_changes
