name: Algolia Reindex

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ALGOLIA_CRAWLER_USER_ID:
        required: true
      ALGOLIA_CRAWLER_API_KEY:
        required: true
      ALGOLIA_API_KEY:
        required: true

jobs:
  algolia-reindex:
    name: Reindex Algolia Search
    runs-on: ubuntu-latest
    steps:
      - name: Run Algolia Crawler
        uses: algolia/algoliasearch-crawler-github-actions@v1
        with:
          crawler-user-id: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
          algolia-app-id: JUYLFQHE7W
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: https://docs.unraid.net
          crawler-name: unraid
